let { permission } = require('./user');
const permissions = {};
permission.map((value) => {
    permissions[value.name] = value.name
})

exports.route = {
    ERP_ADDRESS: "ERP_ADDRESS",
    ERP_CONTACT: "ERP_CONTACT",
    ERP_COUNTRY: "ERP_COUNTRY",
    ERP_CURRENCY: "ERP_CURRENCY",
    ERP_CUSTOMER: "ERP_CUSTOMER",
    ERP_ENTITY: "ERP_ENTITY",
    ERP_GERNERAL: "ERP_GERNERAL",
    ERP_IMAGE: "ERP_IMAGE",
    ERP_ITEM: "ERP_ITEM",
    ERP_LANGUAGE: "ERP_LANGUAGE",
    ERP_NOTIFY: "ERP_NOTIFY",
    ERP_PRODUCT: "ERP_PRODUCT",
    ERP_PROJECT: "ERP_PROJECT",
    ERP_SANDBOX: "ERP_SANDBOX",
    ERP_SECTOR: "ERP_SECTOR",
    ERP_SPECIFICATION: "ERP_SPECIFICATION",
    ERP_VENDOR: "ERP_VENDOR",
    ERP_VENDOR_CONTACT: "ERP_VENDOR_CONTACT",

    /* Finance Route */
    FINANCE_EULER: "FINANCE_EULER",
    FINANCE_INVOICE: "FINANCE_INVOICE",
    FINANCE_PROJECT: "FINANCE_PROJECT",
    FINANCE_PURCHASE_BILL: "FINANCE_PURCHASE_BILL",
    FINANCE_SEPAPAYMENT: "FINANCE_SEPAPAYMENT",

    /* Order Manager */
    ORDER_ITEM: "ORDER_ITEM",

    /* SETTING ROUTE */
    SETTING_FIELD: "SETTING_FIELD",
    SETTING_FIELD_TYPE: "SETTING_FIELD_TYPE",
    SETTING_GENERAL_LEDGER: "SETTING_GENERAL_LEDGER",
    SETTING_VAT_TYPE: "SETTING_VAT_TYPE",

    /* STUDIO */
    STUDIO_ITEM: "STUDIO_ITEM",

    /* Vendor */
    VENDOR_ITEM: "vendor_item",
    VENDOR_QUOTATION: "vendor_quotation",

    /* waive off  */
};
exports.roles = {
    SUPPER_USER: "supper_user",
    SALES_MANAGER: "sales_manager",
    SALES_SENIOR: "sales_senior",
    SALES_EMPLOYEE: "sales_employee",
    ORDER_MANAGER: "order_manager",
    ADMINISTRATION_MANAGER: "administration_manager",
    ADMINISTRATION: "administration",
    ITEM_EMPLOYEE: "item_employee",
    STUDIO: "studio",
    VENDOR_ADMIN: "vendor_admin",
    VENDOR_LIGHT_USER: "vendor_light_user",
    VENDOR_QUOTATION: "vendor_quotation",
};

exports.access_module = ({
    [exports.route.ERP_ADDRESS]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_CONTACT]: [
        permissions.contact,
    ],
    [exports.route.ERP_COUNTRY]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_CURRENCY]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_CUSTOMER]: [
        permissions.customer,

    ],
    [exports.route.ERP_ENTITY]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_GERNERAL]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_IMAGE]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_ITEM]: [

        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,

    ],
    [exports.route.ERP_LANGUAGE]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_NOTIFY]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_PRODUCT]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_PROJECT]: [

        permissions.create_project,
        permissions.project_list,

    ],
    [exports.route.ERP_SANDBOX]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_SECTOR]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_SPECIFICATION]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.ERP_VENDOR]: [
        permissions.add_vendor,
        permissions.vendor_list,
    ],
    [exports.route.ERP_VENDOR_CONTACT]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
    ],
    /* Finance Route */
    [exports.route.FINANCE_EULER]: [
        permissions.euler,
    ],
    [exports.route.FINANCE_INVOICE]: [
        permissions.finance_project,
        permissions.finance_invoice,
    ],
    [exports.route.FINANCE_PROJECT]: [
        permissions.finance_project,
        permissions.finance_invoice,
    ],
    [exports.route.FINANCE_PURCHASE_BILL]: [
        permissions.purchase_bills,
    ],
    [exports.route.FINANCE_SEPAPAYMENT]: [
        permissions.purchase_bills,
    ],
    /* Order manager */
    [exports.route.ORDER_ITEM]: [
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
    ],
    /* SETTING ROUTE */
    [exports.route.SETTING_FIELD]: [
        permissions.settings
    ],
    [exports.route.SETTING_FIELD_TYPE]: [
        permissions.settings
    ],
    [exports.route.SETTING_GENERAL_LEDGER]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    [exports.route.SETTING_VAT_TYPE]: [
        permissions.customer,
        permissions.company,
        permissions.contact,
        permissions.dashboard,
        permissions.create_project,
        permissions.project_list,
        permissions.studio_list,
        permissions.order_manager_list,
        permissions.combi_deals,
        permissions.sent_combi_deals,
        permissions.add_vendor,
        permissions.vendor_list,
        permissions.finance_project,
        permissions.finance_invoice,
        permissions.purchase_bills,
        permissions.euler,
        permissions.user,
        permissions.settings
    ],
    /* STUDIO */
    [exports.route.STUDIO_ITEM]: [

        permissions.studio_list,
    ],
    /* Vendor Route */
    [exports.route.VENDOR_ITEM]: [
        exports.roles.VENDOR_ADMIN,
        exports.roles.VENDOR_LIGHT_USER,
        exports.roles.VENDOR_QUOTATION,
    ],
    [exports.route.VENDOR_QUOTATION]: [
        exports.roles.VENDOR_ADMIN,
        exports.roles.VENDOR_LIGHT_USER,
        exports.roles.VENDOR_QUOTATION,
    ],
})