exports.rolesPermission = {
    supper_user: [
        "dashboard",
        "create_project",
        "project_list",
        "customer",
        "company",
        "contact",
        "studio_list",
        "order_manager_list",
        "combi_deals",
        "sent_combi_deals",
        "add_vendor",
        "vendor_list",
        "finance_project",
        "finance_invoice",
        "purchase_bills",
        "euler",
        "user",
        "settings",
    ],
    sales_manager: [

        "create_project",
        "project_list",
        "customer",
        "company",
        "contact",
        "settings",
        "add_vendor",
        "vendor_list",
    ],
    sales_senior: [

        "create_project",
        "project_list",
        "customer",
        "company",
        "contact",
        "settings",
        "add_vendor",
        "vendor_list",
    ],
    sales_employee: [

        "create_project",
        "project_list",
        "customer",
        "company",
        "contact",
        "settings",
        "add_vendor",
        "vendor_list",
    ],
    order_manager: [
        "order_manager_list",
        "combi_deals",
        "sent_combi_deals",
    ],

    administration_manager: [
        "finance_project",
        "finance_invoice",
        "purchase_bills",
        "euler",
    ],
    administration: [
        "finance_project",
        "finance_invoice",
        "purchase_bills",
        "euler",
    ],
    item_employee: [
        "finance_project",
        "finance_invoice",
        "purchase_bills",
        "euler",
    ],
    studio: [
        "studio_list"
    ],


}

exports.permission = [
    {
        name: "waiveofrequest",
        type: 2, //  means role
        description: "waiveofrequest",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "dashboard",
        type: 2, //  means role
        description: "Dasboard",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "create_project",
        type: 2,
        description: "Create Project",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "project_list",
        type: 2,
        description: "Project List",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "customer",
        type: 2,
        description: "Customer",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "company",
        type: 2,
        description: "Company",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "contact",
        type: 2,
        description: "Contact",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "studio_list",
        type: 2,
        description: "Studio",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },

    {
        name: "order_manager_list",
        type: 2,
        description: "Order Manager",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "combi_deals",
        type: 2,
        description: "Combi Deals",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "sent_combi_deals",
        type: 2,
        description: "Sent Combi Deals",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "add_vendor",
        type: 2,
        description: "Add vendor",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "vendor_list",
        type: 2,
        description: "vendor List",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },

    {
        name: "finance_project",
        type: 2,
        description: "Finance Project",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "finance_invoice",
        type: 2,
        description: "Finance Invoice",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "purchase_bills",
        type: 2,
        description: "Purchase Bills",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "euler",
        type: 2,
        description: "Euler",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "user",
        type: 2,
        description: "User",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "settings",
        type: 2,
        description: "Settings",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
];



exports.user_roles = [
    {
        name: "supper_user",
        type: 1, //  means role
        description: "Super user",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "sales_manager",
        type: 1,
        description: "Sales manager",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "sales_senior",
        type: 1,
        description: "Sales senior",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "sales_employee",
        type: 1,
        description: "Sales employee",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "order_manager",
        type: 1,
        description: "Order manager",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "administration_manager",
        type: 1,
        description: "Administration manager",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },

    {
        name: "administration",
        type: 1,
        description: "Administration",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "item_employee",
        type: 1,
        description: "Item employee",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "studio",
        type: 1,
        description: "Studio",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 1,
    },
    {
        name: "vendor_admin",
        type: 1,
        description: "Admin",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 2,
    },
    {
        name: "vendor_quotation",
        type: 1,
        description: "Quotation",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 2,
    },
    {
        name: "vendor_light_user",
        type: 1,
        description: "Light User",
        createdAt: new Date(),
        updatedAt: new Date(),
        user_type: 2,
    },

];

